language: node_js
node_js:
  - lts/*
script:
  - npm run docs:build
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: master